import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from '@components/Header/Header';

import '@styles/reset.css';
import '@styles/globals.css';
import { Providers } from './providers';
import Footer from '@components/Footer/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    default: 'Nagency',
    template: 'Nagency | %s',
  },
  description: 'Generated by create next app',
};

import favicon_icon from '../../public/favicon.ico';
import Body from '@components/Layouts/Body/Body';
import StoreProvider from '@components/Layouts/StoreProvider/StoreProvider';
import MobileNavList from '@components/Header/MobileNavList/MobileNavList';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <head>
          <link rel="icon" href={favicon_icon.src} sizes="any" />
        </head>
        <Body font={inter.className}>
          <Providers>
            <MobileNavList />
            <Header />
            <main className="main">{children}</main>
            <Footer />
          </Providers>
        </Body>
      </html>
    </StoreProvider>
  );
}
